### ISSUE TITLE
Make updates to the "Listen" tab

### ISSUE THREAD

**Issue by brendanmetzger** [Third-Coast/website#11]
Question for @brendanmetzger —how hard would it be to make "Playlists" a tab under listen, and remove it from the nav bar?

**Comment by brendanmetzger** [comment]
@TCEmkenn, by tab do you mean the actual listen page with all the features listed or the link at the top of the screen?

**Comment by TCEmkenn** [comment]
Hi!

Sorry, yeah. That was SUPER unclear. Is there a way that Playlists could exist within the "Listen" page, as a sub-tab? (I know this might be tricky from a directory standpoint.) 

_So it might be:_ 

All
Stories
Re:sound
Conf Sessions
ShortDocs
Winners
**Playlists**

**Comment by TCEmkenn** [comment]
Hey, 

Just pulling this back up, because I'm super curious! We're interested in playlists being removed from the Nav bar, and tucked into "Listen." Is this possible?

E
