### ISSUE TITLE
"Submit" Button

### ISSUE THREAD

**Issue by TCEmkenn** [Third-Coast/website#17]
Can we enter the "Submit" button graphic to the Competition page, or do you have to do it, Brendan?

**Comment by brendanmetzger** [comment]
You can do it—it's a bit weird to get the button image in place. Do you have the submit link ready? If so I can do it. I'm going to dig around for the image quick. (unless you have one..)

**Comment by TCEmkenn** [comment]
Hiya!

Making it a new submit button as we speak (and was trying to see how it read in the box & maybe futz with it.)

Want to try to instruct me how to do it? 

If not, I can send something over in 20. (We're not officially opening the submissions until 11:59 CST, so I was trying to hold off until 11:59 PM so folks didn't try to get to a password protected form.)

Form is here:  https://thirdcoastfestival.wufoo.com/forms/2020-tcrhdf-competition-submission

**Comment by brendanmetzger** [comment]
I made a little stylesheet adjustment if you want to avoid the button... heres a look

![Screen Shot 2020-04-07 at 5 00 38 PM](https://user-images.githubusercontent.com/4213/78723609-64b11600-78f1-11ea-89e9-4973f51a9ce8.png)

**Comment by brendanmetzger** [comment]
To use that, you just add a link with whatever text you want in the 'extra' textarea

**Comment by TCEmkenn** [comment]
I think I'd like to mess with the button? (Is that OK?) Here's the button: https://drive.google.com/file/d/13ExndbhjqJTJspDgYs4NOhJk1FuziI16/view?usp=sharing

**Comment by brendanmetzger** [comment]
I change the stylesheet to make a link in the extra box look like your button, that seem ok? That way you can edit the text if you want, it can have a hover state, and it's a lil more accessible since it still has text value.

![Screen Shot 2020-04-07 at 5 38 19 PM](https://user-images.githubusercontent.com/4213/78726115-c6c04a00-78f6-11ea-8b73-d526d2d5ed03.png)

**Comment by TCEmkenn** [comment]
Oo, looks great!

**Comment by TCEmkenn** [comment]
Can this button be part of the floating side menu? (So if I scrolled down, I could still click on the "Enter" button no matter where I was on the page?

**Comment by brendanmetzger** [comment]
Yep, that's a good idea.. I'll implement.

**Comment by TCEmkenn** [comment]
We love it! No st
