### ISSUE TITLE
Cohesion in  Competition, Residency, Conference Templates

### ISSUE THREAD

**Issue by brendanmetzger** [Third-Coast/website#2]
- [x] collapsible text
- [x] sidebar movement 
- [x] make all headings inline markup, etc. match
- [x] remove drop shadows [see comment]
- [x] remove location text on conf [see comment]
- [x] ability to add photos or images within articles

**Comment by brendanmetzger** [comment]
depending on the banner situation, there will have to be some finesse here (text on images is tricky, which is usually the case with the banners, ie. 2019). Nutshell, it's a massage to get close to acceptable [contrast ratio guidelines](https://webaim.org/resources/contrastchecker/) but there are probably ways to get the best of both worlds. Re. invisible text, probably worth removal entirely IMO—also, is there a place outside the banner as this is a location field... I'm thinking big picture like having a map/directions or something..

**Comment by TCEmkenn** [comment]
@brendanmetzger Gotcha! This makes sense. (This was in reference to the idea of having photos + text over the photos, so, for example: e.g. A photo of Conference attendees as a banner, with "Conference" around it, right?)

Can you explain this a little more: "Also, is there a place outside the banner as this is a location field... I'm thinking big picture like having a map/directions or something." I'm intrigued...!

**Comment by brendanmetzger** [comment]
correct- text on top of photos is what you need to to enhance contrast for..

re. location, it could go in a sidebar with a map widget or some other location-y doodads to help visitors plan their trip.

**Comment by TCEmkenn** [comment]
Hi hi, 

Just checking in again about collapsible text. We're hoping to get that up and running as soon as possible—did you encounter difficulties there? 

As an example, we were looking at the Sundance page. (Obviously our page looks different, so the style might not be identical, but can you achieve something close to this?) 

https://www.sundance.org/festivals/sundance-film-festival/submit

**Comment by TCEmkenn** [comment]
**Re: Images on articles**

We're interested in figuring out other ways to break up the text on the MAIN Competition page (and therefore, the rest of our main pages.) Is there a way that we can add images (photos or graphics) to individual articles (potentially so they look MORE like the main pages), so that when we link the articles  to the main Competition page, there is a linked image with each article? 

Let me know if this makes sense. Maybe you could make a version on the dev site that we could look at?

**Comment by TCEmkenn** [comment]
**Re: Sidebar Movement**

On the sidebar, we love how the Driehaus logo & previous competition dropdown menu get hidden underneath the sticky menu as you go down—but it happens kind of quickly (especially for the Driehaus logo). Can the "disappearing" function start when you get to the first article (i.e. "Deadlines")?

**Comment by brendanmetzger** [comment]
In order of ? asked
- Collapsable text is v. close, just checking on some things. Do you want me to deploy when I have it done?
- 2 ways to go about this. 1, Images can go within articles at any place with markdown (but it might not look nice until stylesheets rules are put in place to deal with that possibility). 2, —and I think what you are referring to is using an image uploaded in the article in the competition in an automated way, which is also possible. Either way, if you have an image in mind, upload it to an article and let me know
- delaying when the logos get covered I'm pondering now...

**Comment by brendanmetzger** [comment]
Collapsable text is live. If you go to the faq page, I've left 2 questions at the top left to collapse for you to practice/see how it works. There rule is to put 6 hashes (#) in front of a question, and it will create a disclosure widget of whatever text comes next. This change is reflected site-wide on all articles btw.

**Comment by TCEmkenn** [comment]
This looks great! Thank you so much. 

We were curious whether or not this could be implemented to the main pages of the website as well (e.g. Conf/Comp/Residency)? (Or if there's a reason not to?)

**Comment by brendanmetzger** [comment]
Yep, it the collapsible text will work on "article" type weather the page is on its own or embedded in another like on the conf/comp/residency setups right now.
