### ISSUE TITLE
Devs

### ISSUE THREAD

**Issue by TCEmkenn** [Third-Coast/website#20]
Have you watched the TV show "Devs"?

**Comment by brendanmetzger** [comment]
I haven't, but I just got Hulu because this summer (Otis loves Curious George, only avail there) and noticed it. Is it good?

**Comment by TCEmkenn** [comment]
It's weird! Do y'all watch much TV? It's kind of strange, has moments of
violence, is sort of weird & dystopic? IDK. I've never seen anything quite
like it before! I thought it had moments of having kind of an interesting
critique of Silicon Valley!

I remember having a strong feeling of: I wonder what Brendan would think
about this, but I can't remember why! Are y'all TV watchers?

(I loved Curious George as a kid! Otis is not alone.)

*Emily S. Kennedy* | Program Director | Third Coast Festival
<http://thirdcoastfestival.org/>

ekennedy@thirdcoastfestival.org | Pronouns: She/Her/Hers
