### ISSUE TITLE
Newsletter Pop-Up on Website Front Page

### ISSUE THREAD

**Issue by TCEmkenn** [Third-Coast/website#21]
A (hopefully) fairly straightforward project—Re:sound has its last episode on WBEZ next week for awhile, and we're doing a callout on the radio for folks to sign up for our newsletter(s) to stay in touch with us! (I know you've done versions of these in the past for fundraising campaigns?)

Can you create a pop-up window that appears when you visit www.thirdcoastfestival.org that asks you if you'd like to subscribe to our newsletter? 

The text we'd like to see is: 

"STAY CONNECTED! Third Coast has ~gone digital~ in 2020, and we’re bringing you new programming celebrating the art & craft of audio storytelling. Whether you are a producer or an audio fan, sign up for our newsletters to be the first to know about what we have in store."

With a ... button below that says:

"SIGN UP HERE"

And that button would link to a (new!) Newsletter form on our website, which I'll make & send you in the next few days.

Could you do this by the end of this week?

**Comment by brendanmetzger** [comment]
Once you have the link to the form made I can get things in place. How long would you like this to run?

If I have a spare moment I might tweak from the old setup to be a little more compelling with your new copy

**Comment by TCEmkenn** [comment]
Hiya!

I would love it if you tweaked the set-up. Is there a way I could see a screenshot of how it looked in the past? I'm having a hard time remembering at this point. 

It's a good question, re: how long it runs. Can we say two weeks, and maybe we'll extend it?

I'll send you this form tomorrow AM, if that's OK?

EK

**Comment by brendanmetzger** [comment]
![Screen Shot 2020-05-22 at 4 40 25 PM](https://user-images.githubusercontent.com/4213/82716545-9988ea80-9c5d-11ea-9fd0-4a8e96096dcb.png)

I've attached a screen shot of the old setup, and then put something together  [on the dev site](https://dev.thirdcoastfestival.org/) as an alternative. IMO, splash pages only encourage one habitual interaction (clicking the x to close it). An alternative is a banner campaign that stays throughout the visit, but requires no interaction to remove.

**Comment by TCEmkenn** [comment]
Hi hi, 

Let's use this link for now: https://signup.e2ma.net/signup/1400701/1400216/

Hmmm. Gotcha. OK. I can design something if I need to, today, but I'm interested in going with a version of the dev site again?

This is for the Newsletter sign-up, not for a call to donations (YET—we may want to use it for that purpose in a few months!), so I think it should be a lot smaller.

For this one, could you put a bar about 1/8th of the height in our green color (?) and have it say the line we pasted above:

"STAY CONNECTED! Third Coast has gone digital in 2020, and we’re bringing you new programming celebrating the art & craft of audio storytelling. Whether you are a producer or an audio fan, sign up for our newsletters to be the first to know about what we have in store."

Then the button next to it could say, "SIGN UP"?

EK

**Comment by brendanmetzger** [comment]
To clarify, the dev site is the *new* version, so I need to do some tweaking to get everything ironed out, but if you’re interested in that direction I can get it updated tomorrow.
