### ISSUE TITLE
Make Favicon Hi-Res

### ISSUE THREAD

**Issue by TCEmkenn** [Third-Coast/website#25]
Can we make the favicon of pidgey higher-res? Do you need a new logo from me to do that?

**Comment by brendanmetzger** [comment]
@TCEmkenn —are you noticing a particular place it is low res? I think the max for the url address bare is 16px by 16px, but you can specify multiple versions for phones and other things.

That said, I think I have access to the logos, and I'm pretty sure whatever  is up there now is what was on the very first version of the site from way back, so it might be extra clunky and time to replace anyway.

**Comment by TCEmkenn** [comment]
@brendanmetzger hey! It's not the biggest deal in the world, but I'm seeing it on the tab next to the other icons  on other tabs when I'm using Google Chrome, and it looks noticeably pixelated in comparison! Maybe it's worth a refresh, if that's not too time consuming?

**Comment by brendanmetzger** [comment]
I added a new icon—I'm using a non-retina screen, so I can't tell for sure if it will have fixed anything though.

**Comment by TCEmkenn** [comment]
Yes! Looks great on the Dev site. Perfect. Let's do it.
