### ISSUE TITLE
Name searching on website!

### ISSUE THREAD

**Issue by TCEmkenn** [Third-Coast/website#32]
Someone in our community changed their name, and they requested we update it on their website. (The person is Tuck Woodstock, formerly Molly Woodstock.)

I updated their Producer Index entry, and manually changed it everywhere it appears—all of that is good. One question I have for you: when I search their deadname (Molly), it will still appear in the search bar, and will still appear on all of the results that it used to be associated with—but when I click on those results, each individual article/result will have the name change (Tuck) reflected.

Is there any way to have "Molly Woodstock" no longer appear in search results? Does it take time for that to disappear? Is it a cache thing?

**Comment by brendanmetzger** [comment]
@TCEmkenn — Once you change any titles, they should be officially changed universally, so I do believe the search is/was a cache issue. I have only seen 'Tuck' results so far.. so most users won't see a 'Molly' unless they had previously/recently used the search.
