### ISSUE TITLE
Data Analytics

### ISSUE THREAD

**Issue by TCEmkenn** [Third-Coast/website#35]

**Comment by TCEmkenn** [comment]
How much do you know about how we manage data analytics on our website?

**Comment by brendanmetzger** [comment]
I set up the original Google Analytics account ID + some custom event tracking  for Jason G years ago. I have access to the account, and check it once in a blue moon when I need to debug something possibly relating to the amount of traffic coming in. Outside of that, I'm not sure it has been used that much by anyone.

**Comment by TCEmkenn** [comment]
OK, cool! I just was able to login via our thirdcoastfestival@gmail.com
account. Got it. Makes sense!

*Emily S. Kennedy* | Program Director | Third Coast Festival
<http://thirdcoastfestival.org/>

ekennedy@thirdcoastfestival.org | Pronouns: She/Her/Hers
