### ISSUE TITLE
Digital Programming Website Launch Week

### ISSUE THREAD

**Issue by TCEmkenn** [Third-Coast/website#36]
**09/14**
- [X] Connect the WSM Domain to Wix website? 

**09/17**
- [x] Add "Third Place" to the navigation bar on the dev site. It should be "first" before the Competition Page.
- [x] Is there a way that we can add a little flourish, to draw attention to it on the navigation bar? We were thinking about a kind of illustrative underline—maybe a thick brushstroke, or something to that effect? Is that going to violate alllll of the principles of good design on a navigation bar? Or should we try to solve it in a different way (maybe simply by updating the copy on the "announcement" banner).

Like, do you see this brushstroke beneath peoples' names at TNY festival (not on the Nav bar here): https://festival.newyorker.com/home

I wonder if that kind of flourish could be beneath "THIRD PLACE" on the Nav Bar? 

**09/18** @brendanmetzger 
- [x] Can you keep nav bar fonts the same as they were, pre-dev site version from yesterday (uppercase, old font)? 
- [x] Can you get rid of the pink brushstroke on “Third Place”? (I need to do more thinking about this! Thank you for tweaking it.)
- [x] Can the connection go "live" between “Third Place” & our site?
- [x] Can you push the “About” ---> "Who We Are" change live?
- [x] Can you change the “STAY CONNECTED! Third Coast has gone digital in 2020, and we’re bringing you new programming celebrating the art & craft of audio storytelling. Whether you are a producer or an audio fan, sign up for our newsletters to be the first to know about what we have in store.” to read: “PST, THIRD COAST IS BACK THIS FALL — in a new, virtual world. Join us for much-needed audio community & inspiration in: Third Place.” (and link Third Place to the digital programming site).

**If you have time:** 
- [x] Can you replace the homepage header image (“Sharing the Best Audio Stories Worldwide”) to just a solid black color? 
- [x] Can you take out "About Us" on the "About Page" above "Third Coast International Audio Festival"?
- [x] We tried to make collapsible text on the About Page, but it wasn’t working for us. Could you implement that?

**Comment by brendanmetzger** [comment]
All the pieces are in place—can take up to 48 hours, but my hunch is that it is probably ready now.

**Comment by brendanmetzger** [comment]
@TCEmkenn some ?'s

- so the link text 'Third Place' points to 'http://audiofestival.org' ?
-  you can add a flourish to the link, totally possible. Do you have a color palette or design of the site I could see?

**Comment by TCEmkenn** [comment]
Hiya,

Yes!

   - Third Place to point to audiofestival.org!
   - Gonna send you a color palette & design in a sec!

EK

*Emily S. Kennedy* | Program Director | Third Coast Festival
<http://thirdcoastfestival.org/>

ekennedy@thirdcoastfestival.org | Pronouns: She/Her/Hers

**Comment by TCEmkenn** [comment]
Sorry for the delay—color palette is here!

Purple: #4f52a5
Pink: #bd6586
Blue: #6ecfb7
Peachy orange: #f4a495

**Comment by brendanmetzger** [comment]
Ok, [look at dev](https://dev.thirdcoastfestival.org) for a version of all the nav changes

**Comment by TCEmkenn** [comment]
Hey!

Any chance I can see it without the new fonts? (I love that you're thinking
about this/I don't think we're ready to look at them/talk through them as a
team today, haha!)

EK

*Emily S. Kennedy* | Program Director | Third Coast Festival
<http://thirdcoastfestival.org/>

ekennedy@thirdcoastfestival.org | Pronouns: She/Her/Hers

**Comment by brendanmetzger** [comment]
the live site still has the generic "source sans" if you want to do a side by side with dev. Before I put all the old fonts back in double check for me that the slowness load is still happening..

**Comment by TCEmkenn** [comment]
Slowness is still happening for me with the new fonts on dev site, if
that's what you mean?

I think no italicization of Third Place, please!


*Emily S. Kennedy* | Program Director | Third Coast Festival
<http://thirdcoastfestival.org/>

ekennedy@thirdcoastfestival.org | Pronouns: She/Her/Hers

**Comment by brendanmetzger** [comment]
Ok, little checklist cuz I gotta run in a lil bit
- Type treatment on 'Third Place' -- Lose the brush stroke too? Screen shots below—something looks off but maybe I've been looking at things too long
- old fonts back in? 
- slowness I'm stumped. It's not happening for me anymore. Can you make a teeny [screencast in quicktime](https://support.apple.com/guide/quicktime-player/record-your-screen-qtp97b08e666/mac)

![Screen Shot 2020-09-17 at 4 50 22 PM](https://user-images.githubusercontent.com/4213/93532128-02c7f400-f906-11ea-9c0e-2dbde51cff7e.png)
![Screen Shot 2020-09-17 at 4 50 12 PM](https://user-images.githubusercontent.com/4213/93532129-03608a80-f906-11ea-8bb7-28fb0c91c123.png)

-

**Comment by TCEmkenn** [comment]
Hi hi!

OK, thank you!!!! & Sorry!

   - *Type treatment: *Can we keep it overnight, and lose it on the dev
   site in the AM if it still looks funky? I agree, something's off, but I
   want to sit with it fo ra bit?
   - *Old fonts back in for now *(I wanna come back to this convo after
   tomorrow!)
   - I'll do a screencast tomorrow, yes!

Thank you! Are you good to check in briefly tomorrow AM, to link the Dig.
Programming site/make some of these other changes go live?

EK

*Emily S. Kennedy* | Program Director | Third Coast Festival
<http://thirdcoastfestival.org/>

ekennedy@thirdcoastfestival.org | Pronouns: She/Her/Hers

**Comment by brendanmetzger** [comment]
@TCEmkenn 
> Can the connection go "live" between “Third Place” & our site?

I'm not sure I follow—can you clarify this a tad?

> Can you change the “STAY CONNECTED! Third Coast has gone digital...

take out the newsletter signup button?

> Can you push the “About” ---> "Who We Are" change live?

The way code is pushed, everything is roped in together unless specified as a different branch ahead of time, unfortunately

>  We tried to make collapsible text on the About Page...

Right now that is only a feature of articles

**Comment by TCEmkenn** [comment]
- Sorry, for the "connection go live", I meant — can you put Third Place back on the nav bar. 

- Take out the newsletter signup button!

- RE: Can you push the “About” ---> "Who We Are" change live?

"The way code is pushed, everything is roped in together unless specified as a different branch ahead of time, unfortunately."

Oh, so you're making all of these changes at once?

**Comment by brendanmetzger** [comment]
Yeah, ultimately everything is organized as a unit, so pulling/pushing code does not apply to individual changes per se. You can do things separately and merge them together later, but that has to be specified ahead of time because there is kind of a science to it.

**Comment by TCEmkenn** [comment]
I think I get it? So I can't pick and choose things from the dev to go live
at any one point?

/ Can you make the things I listed happen without the dev site right now? I
don't need to preview them! (Sorry if I'm thinking about this all wrong.)

*Emily S. Kennedy* | Program Director | Third Coast Festival
<http://thirdcoastfestival.org/>

ekennedy@thirdcoastfestival.org | Pronouns: She/Her/Hers

**Comment by brendanmetzger** [comment]
Right—dev is preview of whats to come. I've lost track of the list at this point, so I can undo whatever is on dev would be the easiest and redo it later if necessary?

**Comment by brendanmetzger** [comment]
I've put in a black image, so when you are ready to have the black banner on the homepage, drag the black image to the first spot and you should be good.

![Screen Shot 2020-09-18 at 2 01 03 PM](https://user-images.githubusercontent.com/4213/93635144-6eb66500-f9b7-11ea-826c-b99ba935168c.png)

**Comment by TCEmkenn** [comment]
OK, sounds good! The list is all in the "Week of Digital Programming
Website Launch" issue — that's the only thing you need to look at. Under
09.18! Is it helpful if I rewrite it?


*Emily S. Kennedy* | Program Director | Third Coast Festival
<http://thirdcoastfestival.org/>

ekennedy@thirdcoastfestival.org | Pronouns: She/Her/Hers

**Comment by brendanmetzger** [comment]
I'd have to revert to last thursday and overwrite from there to get todays list isolated... which [is all of this](https://github.com/Third-Coast/website/commits/master)

**Comment by TCEmkenn** [comment]
Oh god.

I'm maybe confused why that is, not sure if you have time to explain it.

I think getting Third Place on the navigation bar is the most important
thing to us right now—however you can do that, ASAP?


*Emily S. Kennedy* | Program Director | Third Coast Festival
<http://thirdcoastfestival.org/>

ekennedy@thirdcoastfestival.org | Pronouns: She/Her/Hers

**Comment by brendanmetzger** [comment]
I think we are both confused :)

So, if you only want the today's list to be updated, I'd have to go back to a point in history when none of the other stuff existed and start todays updates in a new branch from there, like a time machine with an alternate reality. Now that I have two separate branches and I can make changes to one without affecting the other, and vice versa.

**Comment by brendanmetzger** [comment]
I think where I am confusing things is that this probably isn't a great idea, because *lots* of stuff has happened between then, resizing the footer logos, about page stuff, address changes, etc.

**Comment by brendanmetzger** [comment]
Sorry, I keep editing this because I feel like I'm explaining everything like a deranged person. Which is somewhat accurate I suppose..

**Comment by TCEmkenn** [comment]
No no, that's fair. Is there any way we can talk on the phone about it? Maybe easier to explain on the phone?

**Comment by brendanmetzger** [comment]
It's aLIVE... erm... aPrOdUcTion.

**Comment by TCEmkenn** [comment]
Yay!!!! It looks beautiful.

*Emily S. Kennedy* | Program Director | Third Coast Festival
<http://thirdcoastfestival.org/>

ekennedy@thirdcoastfestival.org | Pronouns: She/Her/Hers

**Comment by TCEmkenn** [comment]
THANK YOU BRENDAN!!!!!

*Emily S. Kennedy* | Program Director | Third Coast Festival
<http://thirdcoastfestival.org/>

ekennedy@thirdcoastfestival.org | Pronouns: She/Her/Hers
