### ISSUE TITLE
Front Page: Tweaks

### ISSUE THREAD

**Issue by TCEmkenn** [Third-Coast/website#43]
We're working on a "20-year" update to the pidgey logo, on the top left-hand corner of the website. 

It'll be temporary, but I wanted to know what the best way to export that file is to send it to you to add to the website? (Unless I can do it myself, and I'm just not seeing it?)

(There may be a little tweaking/back and forth with it!)

**Comment by brendanmetzger** [comment]
@TCEmkenn - the best format to use would be SVG (original logo can be [downloaded here](https://www.thirdcoastfestival.org/images/skinny-logo.svg)) because it scales to any resolution. That file can be edited in Illustrator or any vector graphics program, and resaved as an svg file. From there you can send back to me to add back to the header.

**Comment by TCEmkenn** [comment]
Any chance you can upload the existing logo with this B&W logo (not Competition — just the color logo)? [You can download the svg file here](https://www.dropbox.com/s/xg3tqfuouqwco5b/TCA001_Logo_Compact_Black.svg?dl=0).

**Comment by brendanmetzger** [comment]
@TCEmkenn -- Couple things quick, addressing your list in order:

1. the new logo is not quite the same aspect. I can change the margins a little, but it won't occupy quite the same space ([seen here](https://dev.thirdcoastfestival.org)).
2. You should be able to edit the 'news & events' text, I'll remove the following paragraph from the template
3. I'll change the text below listen—it is part of the template, and thus, not editable in the current setup.
4. I can hide the extra grey bar, or if you swap out the text with just a blank space you can bypass the text requirement. The gray box will still be there though. If you'd prefer, I can remove it totally, but then will have to put it back in if you do want to use it for something in the future. If that's ok, just confirm and I'll get rid of it
4. can you give me a little more info on what needs to happen with the footer logos?

**Comment by TCEmkenn** [comment]
@brendanmetzger — responses below!

1. I'm a dummy — I'll send the correct one. Give me a sec. 
2. OK, cool. I can edit the text, just not that one line!
3. Thank you for changing that text!
4. I'm cool with hiding the grey bar.
5. Yeah, sorry — I think, when we added a bunch more last year, they ran over onto a second line — so now, when I removed a few of them, they're scrunched up + left justified. Could you make them a bit bigger, and less close together, to better occupy the width of the page? (Does that make sense?)

**Comment by brendanmetzger** [comment]
The gray box *was* editable, but since it will be removed, that opens some utility.  The text that occupied that space will now occupy the space below listen, so you should be able to edit it when you click on the edit button. Those adjustments will go live once the logo is ironed out.

**Comment by TCEmkenn** [comment]
Oh sorry, I know the grey text was editable! I meant the "News & Events" text — is that editable by me?

**Comment by TCEmkenn** [comment]
Correct logo updated above!

**Comment by brendanmetzger** [comment]
@TCEmkenn You can now edit both the title of "news & events" and the text under listen:

 To edit the text of news and events, click the edit button next to it and change the title

![Screen Shot 2021-02-02 at 3 03 22 PM](https://user-images.githubusercontent.com/4213/106662437-ff0cd500-6567-11eb-9d01-01c33478b952.png)

as for the text under the "listen" area, click the edit button in the banner and edit the description. Alas, confusing... but lots of changes over the years! (no more grey box tho)

**Comment by TCEmkenn** [comment]
Ok, this is amazing! Thank you! I like it without the grey bar :)

**Two questions:** 

- [ ] Are you able to make the "Listen" text size & the "Our Latest" (previously "News & Events") the same size — aka, the size of "Our Latest," not "Listen"?
- [ ] I was able to change the title of News & Events, but I wasn't sure what you meant above — can I add/edit/adjust text beneath "News & Events" now, or no?

**Comment by brendanmetzger** [comment]
>  Are you able to make the "Listen" text size & the "Our Latest" (previously "News & Events") the same size — aka, the size of "Our Latest," not "Listen"?

OMG. I just spent awhile looking for why Listen was bigger under mounting exasperation and eventually found the culprit. There is a larger story there, for sure.. another  time I suppose.

>  I was able to change the title of News & Events, but I wasn't sure what you meant above — can I add/edit/adjust text beneath "News & Events" now, or no?

Right now no, as I don't have a template variable to map any text. I'm sure I could probably use the 'extra' field, but I need to investigate that more.

**Comment by TCEmkenn** [comment]
OH NO. I want to hear the story! :) (I'm so sorry.) 

Also, could you switch back our Donate link on both the header & the footer to https://donatenow.networkforgood.org/ThirdCoast

?

That's OK re: "Right now no, as I don't have a template variable to map any text. I'm sure I could probably use the 'extra' field, but I need to investigate that more."!

**Comment by brendanmetzger** [comment]
k - just Switched back the donate link a min ago.

(Re. story... kinda funny, not terribly tragic ;)
