### ISSUE TITLE
Possible technical issue?

### ISSUE THREAD

**Issue by mayags** [Third-Coast/website#51]
Hi hi: This isn't super-urgent, but I just saw this tweet: https://twitter.com/samlistens/status/1571916869539631104 

Emily & I aren't encountering the issue (tho neither of us have Firefox), but any chance you have insight into where the problem could stem from? @brendanmetzger 

Maya

**Comment by brendanmetzger** [comment]
@mayags @TCEmkenn 

Did the tweet get deleted? I don't have Twitter so maybe I just can't see it... in which case post a screenshot and I'll take a look.

**Comment by mayags** [comment]
Hiya: does this work:

<img width="303" alt="Screen Shot 2022-09-21 at 10 36 48 AM" src="https://user-images.githubusercontent.com/8697911/191548349-24f24db0-6acf-4930-9505-fb304997cdf9.png">

**Comment by mayags** [comment]
Hey Brendan: this same person has been tweeting publicly again that the website is "broken." They posted this screenshot for me to see -- I've not encountered this feedback from anyone else, but wanted to circle back: what do you think is the issue at hand? Could it be the settings on their browser?

Thanks!

![Sam Greenspan Screenshot](https://user-images.githubusercontent.com/8697911/196468797-b1e73b37-e2dc-4f32-99de-cde773c59075.jpeg)

**Comment by brendanmetzger** [comment]
@mayags @TCEmkenn

It looks like firefox is automatically loading https://WWW.thirdcoastfestival.org instead  https://thirdcoastfestival.org. I did not generate a certificate for www.

I can probably find a way to get around this somehow or another. In the interim, <https://thirdcoastfestival.org/> is the url to be used that works as it should.

**Comment by mayags** [comment]
Thanks, Brendan! I will relay this to the person asking.

**Comment by TCEmkenn** [comment]
@brendanmetzger @mayags Sorry for the delay on this — this is not an issue that should be solved today, but how difficult would it be to generate a certificate for www?

**Comment by brendanmetzger** [comment]
@TCEmkenn I just generated one now so I wouldn't forget—should be all better.

**Comment by TCEmkenn** [comment]
Oh awesome, thank you!

*Emily S. Kennedy* | Co-Director | Third Coast Festival
<http://thirdcoastfestival.org/>

***@***.*** | Pronouns: She/They
