### ISSUE TITLE
Enter Now button on "category pages"

### ISSUE THREAD

**Issue by mayags** [Third-Coast/website#57]
Hey there @brendanmetzger:

Just wanted to flag that I believe the "Enter Now" button that's hardcoded into the category "child" pages is an incorrect link -- leading people to a page on Paperform that prompts them to make an account. Since I think that's hardcoded, I think we'd you to change that, Brendan? (If not, let me know, and I can make that change!)

I believe this is happening on all of the individual category pages, listed here: https://www.thirdcoastfestival.org/article/competition-categories

The link lands people here: https://paperform.co/

When it should land people here: https://2022thirdcoastcompetition.paperform.co/

Let me know the best way to fix this? Thanks!

Maya

**Comment by brendanmetzger** [comment]
Should be fixed
