### ISSUE TITLE
Foundation Support

### ISSUE THREAD

**Issue by TCEmkenn** [Third-Coast/website#6]
Can you add logos from each of our current foundations to the footer below the footer? (I don't think I have access to this, do I?)

> You can do that in the CMS by changing the image for the org in question. From there, on TCF about page, there are 'sponsors', and if they have the word 'Support' in the connection label, they show up on the about page and the logos show up in the footer. I can make a video showing how to update more specifically if you'd like-bm

The list, in order, should look like: 

AgaDino Foundation
Illinois Arts Council Agency
Manaaki Foundation
National Endowment for the Arts
The Richard H. Driehaus Foundation

Brand Guidelines for the Illinois Arts Council Agency are here: https://arts.illinois.gov/IACLogo

Brand guidelines for the National Endowment for the Arts are here: https://www.arts.gov/grants/manage-your-award/nea-logo

**Comment by TCEmkenn** [comment]
Hi! OK, that was perfect. I got that far! 

Are you able to adjust the column that holds the line: "Thank you to the following foundations for their major support of the Third Coast Festival" to be a little more scrunched? I'm on Chrome on a 13-inch Macbook screen, and the Driehaus logo spills over to the  next line.

**Comment by brendanmetzger** [comment]
yeah—ill figure something out to make the arrangement work!

**Comment by TCEmkenn** [comment]
Thank you!

**Comment by TCEmkenn** [comment]
Last q on this—could you drop "the" and "Festival" from the end of the sentence, and add a period to the end of it, so "Thank you to the following foundations for their major support of the Third Coast Festival," reads: "Thank you to the following foundations for their major support of Third Coast."

**Comment by TCEmkenn** [comment]
Hiya, 

OK, I just added two new foundations + logos (Arts for IL Relief Fund & Illinois Humanities) to the list on the About Page & I want their logos to appear on the footer with the other logos!

Do you have to make them appear somehow on your end, or did I screw it up?

**Comment by brendanmetzger** [comment]
Hmm, I see them?

Images are lazy loaded—meaning they don't load until they become visible, but that sort of gets wonky as you edit the page b/c technically you already saw them. Anyway, refreshing or moving to another page will make them visible.

**Comment by TCEmkenn** [comment]
Ooo... I see them. Got it! Thank you. 

There are so many now!!!!! It makes us look like we're rich! (Sigh. I wish.) 

- Is it possible to make them all a bit smaller, and make them all relatively the same size? 
- Is there a world that they could basically fit on the same line?
- Do you think that if they do appear on two lines, there could be four logos on the first line, and four logos on the second line?

**Comment by brendanmetzger** [comment]
### Is it possible to make them all a bit smaller, and make them all relatively the same size?
> Well, it's the wide ones that become a challenge, so without cropping, that is sort of though to pull off. I did find another logo for the manaaki foundation, but I don't know if it's the real deal as they don't have a press pack or website that I can find any details. Same with aagidino—in fact, when you search for their logo tcf appears to be the only place it is used. Maybe it could be cropped?
![manaaki](https://user-images.githubusercontent.com/4213/93527216-24bd7880-f8fe-11ea-8386-a37371f7da6c.png)

### Is there a world that they could basically fit on the same line? / Do you think that if they do appear on two lines, there could be four logos on the first line, and four logos on the second line?
> Investigating... one line is ideal, but i'll see about wrapping in chunks..

**Comment by TCEmkenn** [comment]
Ooo, interesting re: logos! Ack. OK. I'll ask about AgaDino; pretty sure
that's the old Manaaki logi? Let's hold off on cropping for now?

If you can figure out a wrapping solution that works for you, that would be
great! One line is ideal, I agree ...

*Emily S. Kennedy* | Program Director | Third Coast Festival
<http://thirdcoastfestival.org/>

ekennedy@thirdcoastfestival.org | Pronouns: She/Her/Hers
