### ISSUE TITLE
Title on "About Us" /Staff Page

### ISSUE THREAD

**Issue by TCEmkenn** [Third-Coast/website#62]
@brendanmetzger We just added Eddie, our new staff member, to the "About Us"/Staff Page on the website. We included his title on the backend, but it's not showing up on the frontend of the website. Could you edit it so his title shows up?

**Comment by brendanmetzger** [comment]
yep, edited. when you attach things, the labels don't automatically apply to both pages. So when Eddie's page has his title on the reference to the TCIAF org page, the org page does *not* have a title on it's reference to Eddie—so I added Eddie's title on the TCF page.

I'm guessing at some point there was a need for the titles to be different?  I feel like this *wasn't* how things worked in the past, though I can't recall when (or what/why) that change may have been made. Either way, that's the how things roll for now!

**Comment by TCEmkenn** [comment]
Ah, ok, got it! Thank you, Brendan!

*Emily S. Kennedy* | Co-Director | Third Coast Festival
<http://thirdcoastfestival.org/>

***@***.*** | Pronouns: She/They
