### ISSUE TITLE
2020 TCRHD Competition and Residency pages need to be created

### ISSUE THREAD

**Issue by brendanmetzger** [Third-Coast/website#7]
Right now, the [competitions page](https://www.thirdcoastfestival.org/competition/) showing the 2020 info is actually the landing for both tc/rhd and shortdocs (scroll all the way down to see). That layout is confusing to say the least...  and can/should probably be addressed, but for right now, a 2020 page needs to be created—this is actually why the links and all the other formats look so different.

I've added the sticky nav and all the other accessories to match, but those only exist on individual competition pages, and I'm going to create a wiki page for how to create a competition v. soon and attach that as a comment in this thread.

**Comment by brendanmetzger** [comment]
added a [wiki explainer](https://github.com/Third-Coast/website/wiki/Competitions,-Conferences-and-Residency-Pages). If you'd like to have a call tomorrow morning to alleviate any confusing points, let me know. There may also be some history that may or may not be worth explaining..

**Comment by TCEmkenn** [comment]
Hiya!

I think a call would be super helpful/maybe @mayags + @Isabel-Vazquez already understand this, but I think being on the call together would be useful! (Also some history sounds useful, too?) I'll check with the team + get back to you about timing!

Just a note: In the Wiki, the Third Coast Conference landing page that you link two, 2x (www.thirdcoastfestival.org/conference) doesn't seem to exist when I click on it, nor when I type it into my browser directly?

EK

**Comment by brendanmetzger** [comment]
Good catch—it was broken.. add that to the history lesson I suppose!

**Comment by Isabel-Vazquez** [comment]
Competition page has been created!
https://www.thirdcoastfestival.org/competition/2020-third-coast-richard-h-driehaus-foundation-competition

**Comment by brendanmetzger** [comment]
I'll go ahead and make the main nav point to that page.
