### ISSUE TITLE
Hosting Video Files on Feature pages

### ISSUE THREAD

**Issue by ehustleby** [Third-Coast/website#75]
Hello,

We have a couple of Winners of the 2022-23 RHDF Competition that have accompanying video files (instead of audio files). Is there a way to host video on their feature pages? [Here](https://www.thirdcoastfestival.org/feature/promise-burden-prompt-origin-defense-palette-call) is an example of one of the feature pages we'd like to host a video on.

Thanks,

**Comment by brendanmetzger** [comment]
There is no video hosting available in the current paradigm, though you could link something from Vimeo or YouTube. I'm not sure about using an embed code due to the way templates are composed and particulars of the embed code itself.
