### ISSUE TITLE
Editing the navigation menu at the top of the website.

### ISSUE THREAD

**Issue by brendanmetzger** [Third-Coast/website#84]
- [x] Replace the Third Coast International Audio Festival Image on the far left of the navigation menu with [this blue ribbon image](https://drive.google.com/file/d/1szMbqlHhLLGIKyF76A8Pok3LrNIoY_Z2/view?usp=sharing) that reads “We Need Third Coast.”
- [x] Directly to the right of the image replaced in the preceding bullet point, we would like to add a new navigation menu option that reads “Our Campaign” and links to this page (currently titled “Looking to the Future”). 
- [x] Rename the “Competition” navigation menu option to read “2024 Call for Entries”
- [x] In the navigation menu of the website, replace the “donate” button in the top right corner with [this image](https://drive.google.com/file/d/1ssGl-G8m16ydYBCKu1L-PikU3TdLk8Qq/view?usp=sharing) which hyperlinks to our new [donation page](https://third-coast-festival.networkforgood.com/projects/225135-we-need-third-coast).

**Comment by mayags** [comment]
Here are the details, just in case you need them: 

Replace the Third Coast International Audio Festival Image on the far left of the navigation menu with [this blue ribbon image](https://drive.google.com/file/d/1szMbqlHhLLGIKyF76A8Pok3LrNIoY_Z2/view?usp=sharing) that reads “We Need Third Coast.”
Directly to the right of the image replaced in the preceding bullet point, we would like to add a new navigation menu option that reads “Our Campaign” and links to this page (currently titled “Looking to the Future”). 
Rename the “Competition” navigation menu option to read “2024 Call for Entries”
In the navigation menu of the website, replace the “donate” button in the top right corner with [this image](https://drive.google.com/file/d/1ssGl-G8m16ydYBCKu1L-PikU3TdLk8Qq/view?usp=sharing) which hyperlinks to our new [donation page](https://third-coast-festival.networkforgood.com/projects/225135-we-need-third-coast).
