### ISSUE TITLE
Replace banners on website with this image 

### ISSUE THREAD

**Issue by mayags** [Third-Coast/website#89]
Hi Brendan: 

I'm sorry for this change, but wondering if you can change the banners on the website to reflect the one I've attached instead. Thank you! 

![Main Banner for Board Review](https://github.com/Third-Coast/website/assets/8697911/aceb7619-13da-4b17-a1bb-5d389b314f4d)

**Comment by brendanmetzger** [comment]
@mayags you can add that image by uploading it to the competition page (and homepage) and dragging it to the first position. Should only take a sec, but I won't be able to do it until later tonight when I can get to a laptop
