### ISSUE TITLE
Update the "WE NEED THIRD COAST" select option on the footer menu

### ISSUE THREAD

**Issue by ehustleby** [Third-Coast/website#91]
Please make sure the "WE NEED THIRD COAST" select option on the footer menu links to the [We Need Third Coast Campaign page ](https://www.thirdcoastfestival.org/explore/detail/Bxx)(FKA Looking to the Future).

Currently the select option link to this now nonactive link: https://www.thirdcoastfestival.org/article/looking-to-the-future

**Comment by brendanmetzger** [comment]
If the title changes, the permalink changes. One of the perils of hardlinknig in the templates. I'm switching it to the generic search url... generally lower SEO performance, but I'm splitting hairs, and it's not worth the hassle of breaking the navigation menus.
