### ISSUE TITLE
Grant Us Access to edit the 2024 Competition Page

### ISSUE THREAD

**Issue by ehustleby** [Third-Coast/website#93]
Please grant Third Coast team the ability to edit the [2024 Competition page](https://www.thirdcoastfestival.org/competition/latest) so that we can change the text on the page, and replace the banner to match the one on the [home page](https://www.thirdcoastfestival.org/) (this [banner image](https://drive.google.com/file/d/1kP6e4O9eXbwL76a8rTeSV3bv2Aq3wveo/view?usp=sharing)).

We want to be able to use this [manage login](https://www.thirdcoastfestival.org/manage/login) to be able to edit the page like we can other pages on the website.

**Comment by brendanmetzger** [comment]
The edit button attaches itself to the canonical title of the page, which was removed in the design you provided. I overlooked this fact, but I don't know how to resolve without putting the page back together like it was (which granted, looks funny with the headline text along with the image text). FWIW, I think I mentioned the image text is not actually functional in any way, for non-sighted users (including search engines).

**Comment by ehustleby** [comment]
Copy that!

@brendanmetzger can you at least swap the current banner image on the [2024 Competition page](https://www.thirdcoastfestival.org/competition/latest) with this image [here](https://drive.google.com/file/d/1kP6e4O9eXbwL76a8rTeSV3bv2Aq3wveo/view?usp=sharing)?

**Comment by ehustleby** [comment]
@brendanmetzger We also hope to change the text of the [2024 Competition page](https://www.thirdcoastfestival.org/competition/latest) with this text below:

## The 2024-25 Call for Entries Will Open In July… We Need Your Help To Re-Launch!

### Help us raise $50,000 to restart the independent Third Coast Competition 

Third Coast recently learned that our funding for the Competition had been terminated by our longtime financial supporter.. But we’re fiercely committed to relaunching an independent Third Coast Competition! And we need the community’s support to make this happen. Please [contribute to the We Need Third Coast Campaign](https://third-coast-festival.networkforgood.com/projects/225135-we-need-third-coast), and read more about it [here](https://www.thirdcoastfestival.org/explore/detail/Bxx). #WeNeedThirdCoast

### No Other Competition Like Ours 

There is no other program like our year-round, independent Third Coast Competition & Call for Entries made by makers, for makers! This awards program prioritizes people and craft over profit, expands access and increases equity in the field, and pushes the boundaries of audio storytelling through experimentation and community. 

Over the last four years, Third Coast’s competition has [showcased](https://www.thirdcoastawards.org/) more work than ever before, added two [new categories](https://www.thirdcoastfestival.org/explore/detail/BwZ), broadened eligibility to include work in all languages across all categories, named nearly 100 [Third Coast Finalists](https://www.thirdcoastawards.org/2022-23-finalists), expanded the Third Coast Listening Team and [Final Round Judging](https://www.thirdcoastawards.org/2022-23-judges) program, added new [Pilot Offerings](https://www.thirdcoastfestival.org/article/202223-offerings), and more. And in that time, Third Coast has committed to a collective pricing initiative](https://www.thirdcoastfestival.org/article/collective-pricing-model), a sliding-scale pricing initiative for our Competition (and all of our programs) to ensure that it is accessible to anyone who wants to enter.  

We’ll be sharing more about these initiatives throughout the [We Need Third Coast Campaign](https://third-coast-festival.networkforgood.com/projects/225135-we-need-third-coast) across social media and on our newsletter. For now, you can check out our [2022-23 Competition & Call for Entries](https://www.thirdcoastfestival.org/explore/detail/Bxd) to see these values in action. 

Want to see these initiatives grow? We need the support of both individuals and an influx of institutional support. (Are you an institution? [Please get in touch with us!](info@thirdcoastfestival.org)) 

### We Want To Hear From YOU

For the 2024-25 Competition, we promise to update our [Collective Pricing philosophy](/explore/detail/Bwd), and offer a new set of [Competition Offerings](https://www.thirdcoastfestival.org/explore/detail/Bxu). As always, our staff is committed to listening to every single entry through our [comprehensive review and judging process](/explore/detail/ByC). 

We hope to make our 2024-25 Call for Entries the largest, most global, most accessible and most innovative Competition ever. 

Stay tuned.

[END OF WEBSITE TEXT] 

Will you be able to add in this text for us?

**Comment by brendanmetzger** [comment]
hacked around, try now @ehustleby

**Comment by ehustleby** [comment]
thanks @brendanmetzger Whatever you did allowed us to edit the page! Thanks so much
