### ISSUE TITLE
Current DNS and how to access it

### ISSUE THREAD

**Issue by ehustleby** [Third-Coast/website#94]
Brendan,

There's one more issue we're facing when it comes to sending out our newsletters. 

Maya and Emily are trying to authenticate our domain ([thirdcoastfestival.org](http://thirdcoastfestival.org/)) to ensure that our Emma newsletter doesn't get flagged by email servers when it gets sent out.

It should be a fairly straightforward forward process that we can handle, except that we can't figure out how to access our DNS to make the changes that we need to make. We have an Amazon account, which suggests that we should have our DNS through "Amazon Route 53." That said, when we access our AWS console, it doesn't look like [thirdcoastfestival.org](http://thirdcoastfestival.org/) is configured through Amazon Route 53 and it's unclear to me how else our DNS would be configured. When we try to "Transfer the domain to the Amazon Route 53 account," we get the following error message (see the screenshot below). The error says: "Not transferable: The following domain is unavailable for transfer: [thirdcoastfestival.org](http://thirdcoastfestival.org/). It is locked at the registry. Unlock the domain at the registry and try again."

<img width="1224" alt="Screenshot 2024-05-09 at 5 28 47 PM" src="https://github.com/Third-Coast/website/assets/156235066/9ec22c68-5e79-4e82-8c45-30984b57e169">

This suggests that we have a different DNS Server. Our questions for you are: 

- What is our current DNS + how do we access it to make CNAME + text record changes? 
- Does it make sense for us to transfer our DNS to Amazon Route 53? If so, how can we unlock the domain at the registry?

We intend to do the actual legwork of authenticating the domain for Emma, but we just urgently need these questions answered so we can regain access. 

Thanks Brendan!

**Comment by brendanmetzger** [comment]
I believe the registrar handles dna records, which is wsm domains. @mayags or @TCEmkenn should have the info on that service. I have Johanna's old login too, should that info have gone missing

**Comment by TCEmkenn** [comment]
@brendanmetzger Ah, got it! Thanks, @brendanmetzger.

**Comment by TCEmkenn** [comment]
I think we've solved this — thanks again for your help @brendanmetzger. I'm closing this issue.
